[package]
name = "ss-lite"
version = "0.1.0"
authors = ["qy3u <qy3u@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
